### ISSUE TITLE
0.5.0 roadmap

### ISSUE THREAD

**Issue by gfudenberg** [open2c/bioframe#92]
#### interval operations
- [x] sort_bedframe default w/o view #86 

#### io 
- [x] move encode client to sandbox, move parquet to sandbox
- [x] delete read_ucsc_mrnafile
- [x] sandbox `parse_gtf_attributes()`. 
- [x] add docstrings for: read_tabix, read_pairix, read_bam, etc.
- [x] develop tutorial for fetchers, fileops, & io
- [x] refactor read_gapfile into `fetch_centromeres`
- [x] tests for io

#### Tutorials and Docs
- [x] add a 'how do I' for finding strand-specific upstream/downstream genomic features 

#### Data
- [x] populate the data folder with chromsizes for yeast, celegans, mouse, drosophila, ...

### Future
- [ ] #91
  - [ ] add `on=[]` option for `subtract`, `complement`.
  - [ ] add `on=[]` for `closest()`. challenge is that filtering is done inside the function. consider passing a user-defined filtering function. This could replace `ignore_upstream`, `ignore_overlaps` flags.
- [ ] consider replacing the repeated `get_default_colnames()` and `_verify_columns()` in each ops with either a decorator or a function that does both. 

#### io
- [ ] either refactor `parse_gtf_attributes` as `read_gtf()` with an option to parse, or wrap an existing tool for gtf parsing into a pandas dataframe. 

- [ ] new frontend function for locally stored genome assemblies #107  
  - [ ] tutorial entry
  - [ ] change default for filter_chroms
  - [ ] add a test for the data (e.g. download from original site and check that names & lengths match)
- [ ] allow `extract_centromeres` to accept a path to a file
- [ ] `io.to_bed` function to save bedframe into bed (incl. resorting columns, dropping those not compatible with the bed format, and formatting the comment line) #72
#### bin ops
- [ ] https://github.com/open2c/bioframe/issues/116
- [ ] definitions
- [ ] functions
  - [ ]  `regions_to_bins` to assign binspans to a set of bp spans
  - [ ] `align_tables` #37 

 #### Tutorials and Docs
- [x] add tutorial for finding strand-specific upstream/downstream genomic features

**Comment by nvictus** [comment]
Closing in favor of project
